In [2]:
import numpy as np

print(np.__version__)

1.26.3


In [24]:
print("|%010.01f|" % 255)
print(1.2e3)
print(1.2e-3)

|00000255.0|
1200.0
0.0012


In [37]:
a = np.array(range(10))
print(a[2:7])
print(a*a)
print(a[9:1:-2])
print(a[9:1])

b = range(10)
print(a[9:1:-1])

[2 3 4 5 6]
[ 0  1  4  9 16 25 36 49 64 81]
[9 7 5 3]
[]
[9 8 7 6 5 4 3 2]


In [47]:
a = {'a': 10, 'b': 20, 'c': 30}

print(a)
print(a.keys())
print(a.values())

for key in a.keys():
    print(key)

b = {f'{i}th': i for i in range(10)}

print(b)

for a in b:
    print(a)

{'a': 10, 'b': 20, 'c': 30}
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
a
b
c
{'0th': 0, '1th': 1, '2th': 2, '3th': 3, '4th': 4, '5th': 5, '6th': 6, '7th': 7, '8th': 8, '9th': 9}
0th
1th
2th
3th
4th
5th
6th
7th
8th
9th


In [50]:
a = range(10)
from functools import reduce
print(list(map(lambda x: x * 2, a)))
print(list(filter(lambda x: x % 2 == 0, a)))
print(reduce(lambda x, y: x + y, a))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8]
45


In [67]:
s = "string"

ans = ""
for c in s:
    ans = c + ans

print(ans)
for i in range(len(s)):
    print(s[-i - 1], end="")
print()


print(range(3))

gnirts
gnirts
[0, 1, 2]
